# Generated by Django 5.2 on 2025-05-10 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
