# Generated by Django 5.2 on 2025-05-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_alter_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
